@BloggingPlatformAPI_HostAddress = http://localhost:5199

### POST создать блог

POST {{BloggingPlatformAPI_HostAddress}}/posts
Content-Type: application/json

{
  "title": "Cake recipe",
  "content": "Two eggs. That's all",
  "category": "Cooking",
  "tags": ["Cake", "Baking"]
}

### GET получить блог по ID

GET {{BloggingPlatformAPI_HostAddress}}/posts/4
Accept: application/json

### GET получить все блоги

GET {{BloggingPlatformAPI_HostAddress}}/posts
Accept: application/json

### DELETE удалить блог по ID

DELETE {{BloggingPlatformAPI_HostAddress}}/posts/1
